package com.demcha.examples.invoice;

import java.util.Objects;

import com.demcha.graphcompose.BusinessTheme;
import com.demcha.graphcompose.DocumentSession;
import com.demcha.graphcompose.DocumentTemplate;
import com.demcha.graphcompose.RowBuilder;
import com.demcha.graphcompose.SectionBuilder;
import com.demcha.graphcompose.TableBuilder;

/**
 * Invoice template generated by the Template Coder Agent for
 * revision-001 of the invoice-reference example. The shape follows
 * the "Preferred template shape" in the project plan (§5.6) and the
 * architecture plan committed alongside this file.
 *
 * The template only uses primitives documented by the
 * graphcompose-1.6 skill pack: DocumentSession, DocumentTemplate,
 * BusinessTheme, pageFlow, addRow, addSection, addTable, and the
 * RowBuilder / SectionBuilder / TableBuilder builders. Uncertain
 * method bindings are tagged with TODO(visual-review) instead of
 * being guessed; the Phase 4 validation fixtures will confirm the
 * exact builder surface.
 */
public final class InvoiceTemplate implements DocumentTemplate<InvoiceSpec> {

    private static final int PAGE_SPACING = 16;
    private static final int HERO_PADDING = 8;

    private final BusinessTheme theme;

    public InvoiceTemplate(BusinessTheme theme) {
        this.theme = Objects.requireNonNull(theme, "theme");
    }

    @Override
    public void compose(DocumentSession document, InvoiceSpec spec) {
        Objects.requireNonNull(document, "document");
        Objects.requireNonNull(spec, "spec");
        document.pageFlow(page -> page
                .name("Invoice")
                .spacing(PAGE_SPACING)
                .addRow("Header", row -> renderHeader(row, spec))
                .addSection("Hero", section -> renderHero(section, spec))
                .addRow("Parties", row -> renderParties(row, spec))
                .addTable("LineItems", table -> renderLineItems(table, spec))
                .addSection("Footer", section -> renderFooter(section, spec)));
    }

    private void renderHeader(RowBuilder row, InvoiceSpec spec) {
        // Left column: logo placeholder + company name + muted address line.
        row.addSection("HeaderLeft", section -> {
            // TODO(visual-review): confirm shape-container builder name for
            // the 40x40 mm dark square logo placeholder. The shape is filled
            // with theme.bodyText() and falls back to a flat fill when the
            // data layer does not supply a logo image.
            section.shape("Logo", shape -> shape
                    .size(40, 40)
                    .fill(theme.bodyText()));
            section.text(spec.company().name())
                    .style(theme.headingMedium());
            section.text(spec.company().addressLine())
                    .style(theme.bodyRegular())
                    .color(theme.mutedText());
        });
        // Right column: INVOICE title + invoice number + issue date.
        row.addSection("HeaderRight", section -> {
            section.text("INVOICE")
                    .style(theme.titleLarge())
                    .uppercase(true);
            section.text(spec.invoiceNumber())
                    .style(theme.bodyRegular())
                    .color(theme.mutedText());
            section.text(spec.issueDate())
                    .style(theme.bodyRegular())
                    .color(theme.mutedText());
        });
    }

    private void renderHero(SectionBuilder section, InvoiceSpec spec) {
        // Soft panel with a thin accent strip on the left edge.
        section.background(theme.panelBackground());
        section.padding(HERO_PADDING);
        // TODO(visual-review): confirm corner-radius API on SectionBuilder;
        // a moderate value (around 4 mm) is the current target and will be
        // recorded in visual-review.md until the fixtures pin it down.
        section.cornerRadius(4);
        section.accentStrip(theme.accentPrimary());

        section.addRow("HeroContent", row -> {
            row.addSection("TotalDue", left -> {
                left.text("TOTAL DUE")
                        .style(theme.headingSmall())
                        .uppercase(true)
                        .color(theme.mutedText());
                left.text(spec.totalDue())
                        .style(theme.amountLarge())
                        .color(theme.bodyText());
            });
            row.addSection("DueBy", right -> {
                right.text("DUE BY")
                        .style(theme.headingSmall())
                        .uppercase(true)
                        .color(theme.mutedText());
                right.text(spec.dueDate())
                        .style(theme.amountMedium())
                        .color(theme.bodyText());
            });
        });
    }

    private void renderParties(RowBuilder row, InvoiceSpec spec) {
        row.addSection("BillTo", section ->
                renderContactBlock(section, spec.recipient(), "BILL TO"));
        row.addSection("From", section ->
                renderContactBlock(section, spec.company(), "FROM"));
    }

    private void renderLineItems(TableBuilder table, InvoiceSpec spec) {
        // Column proportions match the reference: 50 / 10 / 20 / 20.
        table.column("Description", 0.50f, TableBuilder.Align.LEFT);
        table.column("Qty", 0.10f, TableBuilder.Align.RIGHT);
        table.column("Unit Price", 0.20f, TableBuilder.Align.RIGHT);
        table.column("Amount", 0.20f, TableBuilder.Align.RIGHT);

        table.headerBackground(theme.tableHeaderBackground());
        table.headerTextColor(theme.tableHeaderText());
        table.zebra(theme.zebraAlternate());
        // TODO(visual-review): confirm the exact builder for repeated
        // headers on TableBuilder. The intent is "preserve the header on
        // every page when the table paginates"; the Phase 4 fixtures
        // ship the verified method name.
        table.repeatHeader(true);

        for (LineItem item : spec.lineItems()) {
            table.row(row -> row
                    .cell(item.description())
                    .cell(item.quantity())
                    .cell(item.unitPrice())
                    .cell(item.amount()));
        }

        // The three summary rows live in a trailing section that visually
        // aligns with the Amount column.
        table.footer(footer -> {
            renderSummaryRow(footer, "Subtotal", spec.subtotal(), false);
            renderSummaryRow(footer, spec.taxLabel(), spec.tax(), false);
            renderSummaryRow(footer, "TOTAL", spec.total(), true);
        });
    }

    private void renderFooter(SectionBuilder section, InvoiceSpec spec) {
        section.text(spec.paymentInstructions())
                .style(theme.bodyRegular());
        section.text(spec.iban() + "  " + spec.swift())
                .style(theme.monospaceRegular());
        section.divider().color(theme.mutedText());
        section.text(spec.contactLine())
                .style(theme.bodyRegular())
                .color(theme.mutedText());
    }

    private void renderContactBlock(SectionBuilder section, Party party, String label) {
        section.text(label)
                .style(theme.headingSmall())
                .uppercase(true)
                .color(theme.mutedText());
        section.text(party.name())
                .style(theme.bodyRegular())
                .color(theme.bodyText());
        for (String line : party.addressLines()) {
            section.text(line)
                    .style(theme.bodyRegular())
                    .color(theme.mutedText());
        }
        section.text(party.country())
                .style(theme.bodyRegular())
                .color(theme.mutedText());
        section.text(party.email())
                .style(theme.bodyRegular())
                .color(theme.mutedText());
    }

    private void renderSummaryRow(SectionBuilder section, String label, String amount,
                                  boolean emphasised) {
        if (emphasised) {
            section.divider().color(theme.mutedText());
        }
        section.addRow(label + "Row", row -> {
            row.addSection(label + "Label", labelSection -> labelSection.text(label)
                    .style(emphasised ? theme.headingMedium() : theme.bodyRegular())
                    .color(theme.bodyText()));
            row.addSection(label + "Value", valueSection -> valueSection.text(amount)
                    .style(emphasised ? theme.amountMedium() : theme.bodyRegular())
                    .color(theme.bodyText()));
        });
    }
}
