#!/usr/bin/env node
/**
 * adapters/codex/install.mjs — make the workflow skills discoverable by Codex.
 *
 *   node adapters/codex/install.mjs [--dest <dir>] [--prefix <p>] [--dry-run] [--uninstall]
 *
 * Codex looks for skills at ~/.codex/skills/<name>/SKILL.md — flat, one
 * directory per skill, no plugin manifest and no nesting. This repository keeps
 * them at skills/workflows/<name>/SKILL.md with four shared reference files
 * beside them, which is what the Claude Code plugin declares.
 *
 * Rather than copying the tree (four copies of the same contract, drifting from
 * the day they are written), each installed skill is a STUB: the frontmatter,
 * which is what makes Codex offer the skill at all, plus the handful of
 * invariants that must hold even if nothing else is read, plus the absolute
 * path of the canonical SKILL.md in this checkout. One extra file read buys a
 * guarantee that the Codex copy cannot say something the source does not.
 *
 * The stubs are regenerated, so re-run this after pulling.
 */

import fs from "node:fs";
import os from "node:os";
import path from "node:path";
import { fileURLToPath } from "node:url";

const repoRoot = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..", "..");
const WORKFLOWS_DIR = path.join(repoRoot, "skills", "workflows");

/** Invariants worth restating in the stub, because they are cheap and load-bearing. */
const ALWAYS = [
  "Never invent GraphCompose API — the pinned pack's `00-api-surface.md` is a closed set.",
  "Every change opens a new revision; never overwrite an APPROVED one.",
  "Resolve the GraphCompose version from the user's build file, never by asking.",
  "Work goes in the user's workspace (`graphcompose-flow/`), not in this checkout.",
];

function usage(code = 0) {
  process.stdout.write(
    "usage: node adapters/codex/install.mjs [--dest <dir>] [--prefix <p>] [--dry-run] [--uninstall]\n\n" +
      "  --dest <dir>    skills directory (default: ~/.codex/skills)\n" +
      "  --prefix <p>    installed skill name prefix (default: graphcompose-)\n" +
      "  --dry-run       print what would be written, write nothing\n" +
      "  --uninstall     remove previously installed stubs\n",
  );
  process.exit(code);
}

function parseArgs(argv) {
  const out = {
    dest: path.join(os.homedir(), ".codex", "skills"),
    prefix: "graphcompose-",
    dryRun: false,
    uninstall: false,
  };
  for (let i = 0; i < argv.length; i += 1) {
    const a = argv[i];
    if (a === "--help" || a === "-h") usage(0);
    else if (a === "--dry-run") out.dryRun = true;
    else if (a === "--uninstall") out.uninstall = true;
    else if (a === "--dest") out.dest = argv[++i];
    else if (a === "--prefix") out.prefix = argv[++i];
    else {
      process.stderr.write(`[codex-install] unknown argument: ${a}\n`);
      usage(2);
    }
  }
  return out;
}

/** Read the frontmatter of a source SKILL.md. */
function readSkill(dir) {
  const file = path.join(WORKFLOWS_DIR, dir, "SKILL.md");
  const source = fs.readFileSync(file, "utf8");
  const match = /^---\r?\n([\s\S]*?)\r?\n---/.exec(source);
  if (!match) throw new Error(`${file} has no frontmatter`);
  const field = (name) => {
    const hit = new RegExp(`^${name}:\\s*(.+)$`, "m").exec(match[1]);
    return hit ? hit[1].trim() : null;
  };
  const description = field("description");
  if (!description) throw new Error(`${file} has no description`);
  return { dir, file, name: field("name") ?? dir, description };
}

function discoverSkills() {
  return fs
    .readdirSync(WORKFLOWS_DIR, { withFileTypes: true })
    .filter((entry) => entry.isDirectory())
    .filter((entry) => fs.existsSync(path.join(WORKFLOWS_DIR, entry.name, "SKILL.md")))
    .map((entry) => readSkill(entry.name))
    .sort((a, b) => a.name.localeCompare(b.name));
}

function stubFor(skill, installedName) {
  // The description is copied verbatim: it is the trigger surface, and a
  // paraphrase here would mean the skill fires in Codex on different words than
  // in Claude Code. The name matches the installed directory, which is the
  // convention every other skill under ~/.codex/skills follows.
  return `---
name: ${installedName}
description: ${skill.description}
---

# ${installedName} (GraphCompose AI Flow)

**Read the canonical skill before doing anything else:**

\`${skill.file}\`

That file is the contract — steps, commands, gates and the references it
links to. This stub exists only so Codex can offer the skill; it is
generated by \`adapters/codex/install.mjs\` and deliberately carries no
copy of the instructions, so it cannot drift from the source.

If the path above does not exist, the checkout moved: re-run
\`node adapters/codex/install.mjs\` from the repository.

## Holds regardless

${ALWAYS.map((line) => `- ${line}`).join("\n")}

## Shell note

Every command in the canonical skill is a plain \`node …\` invocation, so
it runs unchanged in PowerShell, cmd and bash. Do not "translate" them.
`;
}

const args = parseArgs(process.argv.slice(2));
const skills = discoverSkills();
if (skills.length === 0) {
  process.stderr.write(`[codex-install] no skills found under ${WORKFLOWS_DIR}\n`);
  process.exit(1);
}

if (args.uninstall) {
  let removed = 0;
  for (const skill of skills) {
    const dir = path.join(args.dest, `${args.prefix}${skill.dir}`);
    if (!fs.existsSync(dir)) continue;
    console.log(`${args.dryRun ? "would remove" : "removed"} ${dir}`);
    if (!args.dryRun) fs.rmSync(dir, { recursive: true, force: true });
    removed += 1;
  }
  console.log(`\n${removed} stub(s) ${args.dryRun ? "would be " : ""}removed.`);
  process.exit(0);
}

console.log(`[codex-install] source : ${WORKFLOWS_DIR}`);
console.log(`[codex-install] dest   : ${args.dest}${args.dryRun ? "  (dry run)" : ""}\n`);

for (const skill of skills) {
  const installedName = `${args.prefix}${skill.dir}`;
  const dir = path.join(args.dest, installedName);
  const file = path.join(dir, "SKILL.md");
  console.log(`${args.dryRun ? "would write" : "wrote"} ${file}`);
  if (args.dryRun) continue;
  fs.mkdirSync(dir, { recursive: true });
  fs.writeFileSync(file, stubFor(skill, installedName), "utf8");
}

console.log(
  `\n${skills.length} skill(s) ${args.dryRun ? "would be " : ""}installed for Codex.` +
    (args.dryRun ? "" : "\nRe-run after pulling, so the stubs point at the current checkout."),
);
