#!/usr/bin/env node
/**
 * adapters/codex/install.mjs — install the harness for Codex, self-contained.
 *
 *   node adapters/codex/install.mjs [options]
 *
 * Codex looks for skills at ~/.codex/skills/<name>/SKILL.md — flat, one
 * directory per skill, no plugin manifest. This installs two things:
 *
 *   ~/.codex/graphcompose-flow/<version>/   the harness runtime, copied
 *   ~/.codex/skills/graphcompose-<name>/    stubs pointing into that copy
 *
 * The copy is the point. Pointing the stubs at a source checkout meant the
 * skills broke whenever the repository moved, was renamed, was deleted after
 * install, or lived on a drive that was not mounted — and a synced ~/.codex
 * carried paths that were meaningless on the second machine. An installed
 * version does not move.
 *
 * Versioned rather than a single directory, so installing a new release cannot
 * half-overwrite the one a session is currently using; old versions are removed
 * with --prune when you want the disk back.
 *
 * Contributors who want the skills to track their working tree can pass
 * --link, which keeps the old behaviour of pointing at this checkout.
 *
 * *What* is copied is not decided here: the payload, the copy and the
 * dependency install live in adapters/lib/runtime.mjs, so the Gemini adapter
 * installs the same runtime rather than a second opinion of it.
 */

import fs from "node:fs";
import os from "node:os";
import path from "node:path";

import {
  ALWAYS,
  RUNTIME,
  copyRuntime,
  directorySizeKb,
  discoverSkills,
  harnessVersion,
  installRuntimeDeps,
  missingBuilds,
  repoRoot,
  WORKFLOWS_DIR,
} from "../lib/runtime.mjs";

function usage(code = 0) {
  process.stdout.write(
    "usage: node adapters/codex/install.mjs [options]\n\n" +
      "  --home <dir>    where the runtime is installed (default: ~/.codex/graphcompose-flow)\n" +
      "  --dest <dir>    skills directory (default: ~/.codex/skills)\n" +
      "  --prefix <p>    installed skill name prefix (default: graphcompose-)\n" +
      "  --link          point the skills at THIS checkout instead of copying\n" +
      "                  (for contributors: the skills then track your working tree)\n" +
      "  --skip-deps     do not run npm ci inside the copy\n" +
      "  --skip-build-check  copy even when the build outputs are missing. The result\n" +
      "                  is NOT a working install; for CI and packaging only\n" +
      "  --prune         remove installed versions other than this one\n" +
      "  --dry-run       print what would happen, change nothing\n" +
      "  --uninstall     remove the stubs, and the runtime under --home\n",
  );
  process.exit(code);
}

function parseArgs(argv) {
  const out = {
    home: path.join(os.homedir(), ".codex", "graphcompose-flow"),
    dest: path.join(os.homedir(), ".codex", "skills"),
    prefix: "graphcompose-",
    link: false,
    skipDeps: false,
    skipBuildCheck: false,
    prune: false,
    dryRun: false,
    uninstall: false,
  };
  for (let i = 0; i < argv.length; i += 1) {
    const a = argv[i];
    if (a === "--help" || a === "-h") usage(0);
    else if (a === "--dry-run") out.dryRun = true;
    else if (a === "--uninstall") out.uninstall = true;
    else if (a === "--link") out.link = true;
    else if (a === "--skip-deps") out.skipDeps = true;
    else if (a === "--skip-build-check") out.skipBuildCheck = true;
    else if (a === "--prune") out.prune = true;
    else if (a === "--home") out.home = argv[++i];
    else if (a === "--dest") out.dest = argv[++i];
    else if (a === "--prefix") out.prefix = argv[++i];
    else {
      process.stderr.write(`[codex-install] unknown argument: ${a}\n`);
      usage(2);
    }
  }
  return out;
}

function stubFor(skill, installedName, runtimeRoot, linked) {
  const skillPath = path.join(runtimeRoot, "skills", "workflows", skill.dir, "SKILL.md");
  return `---
name: ${installedName}
description: ${skill.description}
---

# ${installedName} (GraphCompose AI Flow)

**Read the canonical skill before doing anything else:**

\`${skillPath}\`

That file is the contract — steps, commands, gates and the references it
links to. This stub exists only so Codex can offer the skill; it is
generated by \`adapters/codex/install.mjs\` and deliberately carries no
copy of the instructions, so it cannot drift from the source.

Run the commands it gives you from the harness root:

\`${runtimeRoot}\`
${
  linked
    ? "\n> Installed with `--link`: that path is a source checkout, so the skill\n> tracks your working tree — and breaks if the checkout moves.\n"
    : ""
}
## Holds regardless

${ALWAYS.map((line) => `- ${line}`).join("\n")}

## Shell note

Every command in the canonical skill is a plain \`node …\` invocation, so
it runs unchanged in PowerShell, cmd and bash. Do not "translate" them.
`;
}

const args = parseArgs(process.argv.slice(2));
const version = harnessVersion();
const skills = discoverSkills();
if (skills.length === 0) {
  process.stderr.write(`[codex-install] no skills found under ${WORKFLOWS_DIR}\n`);
  process.exit(1);
}

// --- uninstall ---------------------------------------------------------------
if (args.uninstall) {
  let removed = 0;
  for (const skill of skills) {
    const dir = path.join(args.dest, `${args.prefix}${skill.dir}`);
    if (!fs.existsSync(dir)) continue;
    console.log(`${args.dryRun ? "would remove" : "removed"} ${dir}`);
    if (!args.dryRun) fs.rmSync(dir, { recursive: true, force: true });
    removed += 1;
  }
  if (fs.existsSync(args.home)) {
    console.log(`${args.dryRun ? "would remove" : "removed"} ${args.home}`);
    if (!args.dryRun) fs.rmSync(args.home, { recursive: true, force: true });
  }
  console.log(`\n${removed} stub(s) ${args.dryRun ? "would be " : ""}removed.`);
  process.exit(0);
}

// --- resolve the runtime root ------------------------------------------------
const runtimeRoot = args.link ? repoRoot : path.join(args.home, version);

if (!args.link && !args.skipBuildCheck) {
  const unbuilt = missingBuilds();
  if (unbuilt.length > 0) {
    process.stderr.write(
      "[codex-install] the harness is not built, so there is nothing to install:\n" +
        unbuilt.map((rel) => `  missing ${rel}\n`).join("") +
        "\nRun the one-time setup from the repository root first:\n\n    npm run setup\n",
    );
    process.exit(69); // EX_UNAVAILABLE — same code the CLIs use when unbuilt
  }
}

console.log(`[codex-install] version : ${version}`);
console.log(`[codex-install] runtime : ${runtimeRoot}${args.link ? "  (linked checkout)" : ""}`);
console.log(`[codex-install] skills  : ${args.dest}${args.dryRun ? "   (dry run)" : ""}\n`);

// --- copy the runtime --------------------------------------------------------
if (!args.link) {
  if (args.dryRun) {
    console.log(`would copy ${RUNTIME.length} path(s) into ${runtimeRoot}`);
  } else {
    let files;
    try {
      // With --skip-build-check the build outputs are legitimately absent.
      files = copyRuntime(runtimeRoot, { tolerateMissing: args.skipBuildCheck });
    } catch (err) {
      process.stderr.write(`[codex-install] ${err.message}\n`);
      process.exit(1);
    }
    console.log(`copied ${files} file(s), ${directorySizeKb(runtimeRoot)} KB`);

    if (!args.skipDeps) {
      for (const failure of installRuntimeDeps(runtimeRoot, (line) => process.stdout.write(line))) {
        process.stderr.write(
          `[codex-install] npm failed in ${failure.pkg}. The install is otherwise complete; ` +
            `run npm ci --omit=dev there yourself, or re-run with --skip-deps.\n` +
            `${failure.error}\n`,
        );
      }
    }
  }
}

// --- write the stubs ---------------------------------------------------------
for (const skill of skills) {
  const installedName = `${args.prefix}${skill.dir}`;
  const file = path.join(args.dest, installedName, "SKILL.md");
  console.log(`${args.dryRun ? "would write" : "wrote"} ${file}`);
  if (args.dryRun) continue;
  fs.mkdirSync(path.dirname(file), { recursive: true });
  fs.writeFileSync(file, stubFor(skill, installedName, runtimeRoot, args.link), "utf8");
}

// --- prune older versions ----------------------------------------------------
if (args.prune && fs.existsSync(args.home)) {
  for (const entry of fs.readdirSync(args.home, { withFileTypes: true })) {
    if (!entry.isDirectory() || entry.name === version) continue;
    console.log(`${args.dryRun ? "would prune" : "pruned"} ${path.join(args.home, entry.name)}`);
    if (!args.dryRun) fs.rmSync(path.join(args.home, entry.name), { recursive: true, force: true });
  }
}

console.log(
  `\n${skills.length} skill(s) ${args.dryRun ? "would be " : ""}installed for Codex.` +
    (args.link
      ? "\nLinked to this checkout — re-run without --link for an install that survives moving it."
      : "\nThe source checkout is no longer needed; this install is self-contained."),
);
