/*
 * Runner for the ${DISPLAY_NAME} template.
 *
 * Generated by graphcompose-ai-flow from templates/${TEMPLATE_ID}/template.json.
 * It is a static file with a handful of names substituted into it — no model
 * decided anything here, and nothing in it is specific to this document beyond
 * those names. Edit it freely; it will not be regenerated over the top of you.
 *
 * To produce a different document, edit ${TEMPLATE_DIR}/${RUNTIME_DATA_NAME}.
 * The layout lives in the template class and rarely needs to change.
 */
import com.demcha.compose.GraphCompose;
import com.demcha.compose.document.api.DocumentPageSize;
import com.demcha.compose.document.api.DocumentSession;

import java.nio.file.Path;

public final class Main {

    public static void main(String[] args) throws Exception {
        Path templateDir = Path.of("${TEMPLATE_DIR}");
        Path output = Path.of(args.length > 0 ? args[0] : "${OUTPUT_FILE}");

        // Where the template finds its data file, its icons and its asset
        // manifest. Both names are set on purpose: `template.dir` is what a
        // published bundle should read, and `revision.dir` is what bundles
        // published by earlier versions of the harness actually read. Drop the
        // second line once the template you are using reads the first.
        System.setProperty("graphcompose.template.dir", templateDir.toString());
        System.setProperty("graphcompose.revision.dir", templateDir.toString());

        if (output.getParent() != null) {
            java.nio.file.Files.createDirectories(output.getParent());
        }

        try (DocumentSession session = GraphCompose.document(output)
                .pageSize(DocumentPageSize.${PAGE_SIZE})
                .create()) {

            ${SPEC_DECLARATION}new ${TEMPLATE_CLASS}()
                    .compose(session${SPEC_ARGUMENT});

            session.buildPdf();
        }

        System.out.println("wrote " + output.toAbsolutePath());
    }
}
