#!/usr/bin/env node
/**
 * scripts/scaffold-runner.mjs — give a project something that can render.
 *
 *   node scripts/scaffold-runner.mjs --project <id> --package com.example.invoice
 *
 * A project created by `init-workspace` has a reference, a revision and no way
 * to turn Java into a PDF. The render runtime needs a Maven module beside the
 * revisions — one that pulls the pinned GraphCompose, pulls the bundled fonts
 * (which moved out of the core artifact at 1.8.0), copies the revision's
 * template into generated sources, and adds that directory to the compile path.
 * That is about a hundred lines of pom whose antrun and build-helper wiring is
 * documented nowhere, and until now every run wrote it from scratch.
 *
 * The bundled seeds do not cover it: the only one is written against 1.7 and is
 * refused on a 2.x project, correctly — seeding a template that cannot compile
 * would be worse. So a 2.x project had no path to a first render that did not
 * go through an agent inventing a build file.
 *
 * What this does NOT write is the spec, the provider and the template. Those
 * model the document and are the authoring work; this is the scaffolding that
 * work stands on.
 *
 * Exit: 0 written · 1 refused (already present, or the version has no mapping)
 *       2 usage · 3 no such project
 */

import fs from "node:fs";
import path from "node:path";

import {
  describeWorkspaceLine,
  projectDir as workspaceProjectDir,
  resolveWorkspace,
} from "./lib/workspace.mjs";

function usage(code = 0) {
  process.stdout.write(
    "usage: node scripts/scaffold-runner.mjs --project <id> [options]\n\n" +
      "  --project <id>      the project to scaffold a render runner for\n" +
      "  --package <pkg>     Java package for the generated template (default: com.example.<docKind>)\n" +
      "  --class <Name>      generated template class (default: Generated<DocKind>Template)\n" +
      "  --doc-kind <kind>   invoice | cv | proposal | coverletter | report (default: from the project)\n" +
      "  --root <dir>        workspace override\n" +
      "  --force             overwrite an existing render-runner/pom.xml\n" +
      "  --json              machine-readable result\n\n" +
      "exit: 0 written | 1 refused | 2 usage | 3 no such project\n",
  );
  process.exit(code);
}

function parseArgs(argv) {
  const out = { project: null, package: null, class: null, docKind: null, root: null, force: false, json: false };
  for (let i = 0; i < argv.length; i += 1) {
    const a = argv[i];
    if (a === "--help" || a === "-h") usage(0);
    else if (a === "--json") out.json = true;
    else if (a === "--force") out.force = true;
    else if (a === "--project" || a === "-p") out.project = argv[++i];
    else if (a === "--package") out.package = argv[++i];
    else if (a === "--class") out.class = argv[++i];
    else if (a === "--doc-kind") out.docKind = argv[++i];
    else if (a === "--root") out.root = argv[++i];
    else usage(2);
  }
  return out;
}

/**
 * Which bundled-font artifact a GraphCompose line expects.
 *
 * The fonts left the core artifact at 1.8.0 and are versioned independently, so
 * there is no 1.1.0-shaped mapping to guess: 2.2.0 pins fonts 1.1.0. A template
 * that asks for `FontName.LATO` without this on the classpath fails at render
 * with "Bundled font resource not found", which reads like a template bug.
 */
function fontsVersionFor(graphComposeVersion) {
  const [major, minor] = graphComposeVersion.split(".").map(Number);
  if (Number.isNaN(major)) return null;
  if (major > 1 || (major === 1 && minor >= 8)) return "1.1.0";
  return null; // before 1.8 the fonts are inside the core artifact
}

const TITLE_CASE = (s) => s.charAt(0).toUpperCase() + s.slice(1);

function pom({ artifactId, graphComposeVersion, fontsVersion, packageName, className }) {
  const packagePath = packageName.split(".").join("/");
  const fontsDependency = fontsVersion
    ? `    <!--
      Bundled Google fonts moved out of the core artifact in 1.8.0 and are
      versioned independently. Without this a template asking for
      FontName.LATO fails at render with "Bundled font resource not found",
      which reads like a template bug and is not one.
    -->
    <dependency>
      <groupId>io.github.demchaav</groupId>
      <artifactId>graph-compose-fonts</artifactId>
      <version>\${graphcompose.fonts.version}</version>
    </dependency>
`
    : "";

  return `<?xml version="1.0" encoding="UTF-8"?>
<!--
  Render runner for this template project.

  Generated by scripts/scaffold-runner.mjs. Its one job is to compile the
  revision's generated template against the pinned GraphCompose and hand the
  render runtime a classpath. The revision to build is chosen by
  -Drevision.id=<id>, which the runtime passes.
-->
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
  <modelVersion>4.0.0</modelVersion>
  <groupId>com.demchaav.graphcompose-flow</groupId>
  <artifactId>${artifactId}</artifactId>
  <version>0.1.0-SNAPSHOT</version>
  <packaging>jar</packaging>

  <properties>
    <maven.compiler.source>21</maven.compiler.source>
    <maven.compiler.target>21</maven.compiler.target>
    <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
    <graphcompose.version>${graphComposeVersion}</graphcompose.version>
${fontsVersion ? `    <graphcompose.fonts.version>${fontsVersion}</graphcompose.fonts.version>\n` : ""}    <revision.id>revision-001</revision.id>
    <revision.generated.sources>\${project.build.directory}/generated-sources/revision</revision.generated.sources>
  </properties>

  <dependencies>
    <dependency>
      <groupId>io.github.demchaav</groupId>
      <artifactId>graph-compose</artifactId>
      <version>\${graphcompose.version}</version>
    </dependency>
${fontsDependency}    <!-- The spec provider reads the revision's data file. -->
    <dependency>
      <groupId>com.fasterxml.jackson.core</groupId>
      <artifactId>jackson-databind</artifactId>
      <version>2.17.2</version>
    </dependency>
  </dependencies>

  <build>
    <plugins>
      <plugin>
        <groupId>org.apache.maven.plugins</groupId>
        <artifactId>maven-antrun-plugin</artifactId>
        <version>3.1.0</version>
        <executions>
          <execution>
            <id>copy-selected-revision-template</id>
            <phase>generate-sources</phase>
            <goals>
              <goal>run</goal>
            </goals>
            <configuration>
              <target>
                <mkdir dir="\${revision.generated.sources}/${packagePath}"/>
                <!--
                  Accept either the Java-canonical "${className}.java" name or
                  the flow's "generated-template.java". The canonical name wins
                  when both exist.
                -->
                <condition property="revision.template.source"
                           value="\${project.basedir}/../revisions/\${revision.id}/${className}.java"
                           else="\${project.basedir}/../revisions/\${revision.id}/generated-template.java">
                  <available file="\${project.basedir}/../revisions/\${revision.id}/${className}.java"/>
                </condition>
                <copy
                    file="\${revision.template.source}"
                    tofile="\${revision.generated.sources}/${packagePath}/${className}.java"
                    overwrite="true"/>
              </target>
            </configuration>
          </execution>
        </executions>
      </plugin>
      <plugin>
        <groupId>org.codehaus.mojo</groupId>
        <artifactId>build-helper-maven-plugin</artifactId>
        <version>3.6.0</version>
        <executions>
          <execution>
            <id>add-selected-revision-source</id>
            <phase>generate-sources</phase>
            <goals>
              <goal>add-source</goal>
            </goals>
            <configuration>
              <sources>
                <source>\${revision.generated.sources}</source>
              </sources>
            </configuration>
          </execution>
        </executions>
      </plugin>
      <plugin>
        <groupId>org.apache.maven.plugins</groupId>
        <artifactId>maven-compiler-plugin</artifactId>
        <version>3.13.0</version>
      </plugin>
    </plugins>
  </build>
</project>
`;
}

// --- run ---------------------------------------------------------------------

const args = parseArgs(process.argv.slice(2));
if (!args.project) usage(2);

const workspace = resolveWorkspace({ explicitRoot: args.root ?? null });
const banner = describeWorkspaceLine(workspace);
if (banner && !args.json) console.log(banner);

const projectDir = workspaceProjectDir(workspace, args.project);
const projectFile = path.join(projectDir, "template-project.json");
if (!fs.existsSync(projectFile)) {
  process.stderr.write(`[scaffold-runner] project not found: ${projectFile}\n`);
  process.exit(3);
}

const project = JSON.parse(fs.readFileSync(projectFile, "utf8"));
const graphComposeVersion = project.targetGraphComposeVersion;
if (!graphComposeVersion) {
  process.stderr.write(
    `[scaffold-runner] ${args.project} has no targetGraphComposeVersion; ` +
      `resolve it first: node scripts/resolve-version.mjs --project-dir <java-project>\n`,
  );
  process.exit(1);
}

const docKind = args.docKind ?? project.docKind ?? "doc";
const packageName = args.package ?? `com.example.${docKind}`;
const className = args.class ?? `Generated${TITLE_CASE(docKind)}Template`;
const fontsVersion = fontsVersionFor(graphComposeVersion);

const runnerDir = path.join(projectDir, "render-runner");
const pomPath = path.join(runnerDir, "pom.xml");
if (fs.existsSync(pomPath) && !args.force) {
  process.stderr.write(
    `[scaffold-runner] ${path.relative(projectDir, pomPath)} already exists; pass --force to replace it\n`,
  );
  process.exit(1);
}

fs.mkdirSync(path.join(runnerDir, "src", "main", "java", ...packageName.split(".")), { recursive: true });
fs.writeFileSync(
  pomPath,
  pom({
    artifactId: `${args.project}-render-runner`,
    graphComposeVersion,
    fontsVersion,
    packageName,
    className,
  }),
  "utf8",
);

// The render block is the other half: without it the runtime does not know
// which class to instantiate, and a project with a runner and no render block
// still cannot render.
project.docKind = docKind;
project.render = {
  ...(project.render ?? {}),
  templateClass: `${packageName}.${className}`,
  dataFileName: `${docKind}-data.json`,
  pages: project.render?.pages ?? 1,
};
project.specClass = project.specClass ?? `${packageName}.${TITLE_CASE(docKind)}Spec`;
project.specProviderClass = project.specProviderClass ?? `${packageName}.${TITLE_CASE(docKind)}SpecProvider`;
project.render.specProviderClass = project.specProviderClass;
project.updatedAt = new Date().toISOString();
fs.writeFileSync(projectFile, `${JSON.stringify(project, null, 2)}\n`, "utf8");

const result = {
  project: args.project,
  runner: path.relative(projectDir, pomPath).split(path.sep).join("/"),
  packageName,
  className,
  graphComposeVersion,
  fontsVersion,
  render: project.render,
  writeNext: [
    `render-runner/src/main/java/${packageName.split(".").join("/")}/${TITLE_CASE(docKind)}Spec.java`,
    `render-runner/src/main/java/${packageName.split(".").join("/")}/${TITLE_CASE(docKind)}SpecProvider.java`,
    `revisions/<revision-id>/generated-template.java`,
  ],
};

if (args.json) {
  process.stdout.write(`${JSON.stringify(result, null, 2)}\n`);
} else {
  console.log(`[scaffold-runner] ${args.project}: wrote ${result.runner} for GraphCompose ${graphComposeVersion}`);
  console.log(`  template class: ${packageName}.${className}`);
  console.log(`  still yours to write:`);
  for (const file of result.writeNext) console.log(`    ${file}`);
}
